import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { DotPattern } from "@/components/ui/dot-pattern";
import NavBar from "@/modules/components/Shared/NavBar/NavBar";
import Footer from "@/modules/components/Shared/Footer/Footer";
import SmoothScroll from "@/components/ui/smooth-scroll";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${outfit.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <DotPattern />
        <SmoothScroll>
          <header>
            <NavBar />
            <div aria-hidden className="h-(--nav-h) shrink-0" />
          </header>
          <main className="flex-1">{children}</main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
